Turn off client ip preservation
18F/identity-gitlab pull request #60
Opened 2021-07-15 20:00 UTC by sharms

When attempting to reach the NLB, if the client IP is preserved, EKS will attempt to route the response directly rather than reply through the NLB, leading to a connection reset.

2021-07-15 20:01 UTC, mitchellhenke approved these changes

2021-07-15 20:05 UTC, timothy-spencer approved these changes
YESS

2021-07-16 00:06 UTC, akrito requested changes

2021-07-16 00:06 UTC, akrito commented on clusters/gitlab-cluster/gitlab/gitlab.yaml
>              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
This should be deleted. It's redefined below.

2021-07-16 00:25 UTC, akrito commented on clusters/gitlab-cluster/gitlab/gitlab.yaml
>              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
Also "proxy-protocol" was latent until this change, but it enables v2, which looks like breaks us. Please delete that line above.

2021-07-16 13:49 UTC, timothy-spencer requested changes

2021-07-16 13:49 UTC, timothy-spencer commented on clusters/gitlab-cluster/gitlab/gitlab.yaml
> +            service.beta.kubernetes.io/aws-load-balancer-type: external
Hold on, we don't want this to be external.  We want it internal.

2021-07-16 13:51 UTC, timothy-spencer commented on clusters/gitlab-cluster/gitlab/gitlab.yaml
> +            service.beta.kubernetes.io/aws-load-balancer-type: external
Oh wait, nevermind.  These annotations are confusing.  Sorry!

2021-07-16 13:52 UTC, timothy-spencer approved these changes

2021-07-16 15:12 UTC, akrito approved these changes
LGTM

2021-07-16 16:48 UTC, merged